{
 "title": "KubeDB / Druid / Summary / druid / druid-sample",
 "description": "The dashboard is designed for KubeDB managed Druid",
 "tags": [
  "db",
  "stats",
  "kubedb",
  "druid"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Status",
   "type": "stat",
   "description": "Represent database status",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_status_phase{namespace=\"druid\", app=\"druid-sample\"} == 1\n",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Druid CR Name",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_info{namespace=\"druid\", app=\"druid-sample\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Require Secure Transport",
   "type": "stat",
   "description": "When this option is enabled, connections attempted using insecure transport will be rejected.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_info{namespace=\"druid\", app=\"druid-sample\"}",
     "legendFormat": "{{requireSSL}}"
    }
   ]
  },
  {
   "title": "Termination Policy",
   "type": "stat",
   "description": "KubeDB Database Resource terminationPolicy",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_info{namespace=\"druid\", app=\"druid-sample\"}",
     "legendFormat": "{{terminationPolicy}}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "description": "Total node count of Druid cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_replicas{namespace=\"druid\",app=\"druid-sample\"}"
    }
   ]
  },
  {
   "title": "CPU Request (Core)",
   "type": "stat",
   "description": "Initial Requested CPU amount by Druid Instance",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_resource_request_cpu{namespace=\"druid\", app=\"druid-sample\"}"
    }
   ]
  },
  {
   "title": "CPU Limit (Core)",
   "type": "stat",
   "description": "CPU Limit in core by Druid instance",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_resource_limit_cpu{namespace=\"druid\", app=\"druid-sample\"}"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "description": "Initial Requested Memory amount by Druid Instance",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_resource_request_memory{namespace=\"druid\", app=\"druid-sample\"}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "description": "KubeDB Druid Total Memory Limit",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_resource_limit_memory{namespace=\"druid\", app=\"druid-sample\"}"
    }
   ]
  },
  {
   "title": "Storage Request",
   "type": "stat",
   "description": "Total storage request by Druid nodes",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_druid_resource_request_storage{namespace=\"druid\", app=\"druid-sample\"}"
    }
   ]
  },
  { "title": "CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Druid Down",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(druid_service_heartbeat{job=\"druid-sample-stats\",namespace=\"druid\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ZK Disconnected",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(druid_zk_connected{job=\"druid-sample-stats\",namespace=\"druid\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage by Druid pods",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}[5m])) * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, max by (namespace, pod, node) (kube_pod_info{node!=\"\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}))) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Druid Phase Not Ready",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubedb_com_druid_status_phase{app=\"druid-sample\",namespace=\"druid\",phase=\"NotReady\"}",
     "legendFormat": "{{druid}}"
    }
   ]
  },
  {
   "title": "Druid Critical Phase",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubedb_com_druid_status_phase{app=\"druid-sample\",namespace=\"druid\",phase=\"Critical\"}",
     "legendFormat": "{{druid}}"
    }
   ]
  },
  {
   "title": "CPU Usage Percentage",
   "type": "graph",
   "description": "CPU Usage  Percentage by Druid pods",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}[5m])) * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, max by (namespace, pod, node) (kube_pod_info{node!=\"\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}))) by (pod) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"druid\", pod=~\"druid-sample-.+$\"} * on (namespace,pod) group_left () max by (namespace,pod) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "description": "CPU Quote information in details",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}[5m])) * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, max by (namespace, pod, node) (kube_pod_info{node!=\"\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}))) by (pod) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"druid\", pod=~\"druid-sample-.+$\"} * on (namespace,pod) group_left () max by (namespace,pod) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"druid\", pod=~\"druid-sample-.+$\"} * on (namespace,pod) group_left () max by (namespace,pod) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)"
    },
    {
     "expr": "sum(sum by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}[5m])) * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, max by (namespace, pod, node) (kube_pod_info{node!=\"\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}))) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"druid\", pod=~\"druid-sample-.+$\"} * on (namespace,pod) group_left() max by (namespace, pod) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)"
    },
    {
     "expr": "sum(sum by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}[5m])) * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, max by (namespace, pod, node) (kube_pod_info{node!=\"\",namespace=\"druid\", pod=~\"druid-sample-.+$\"}))) by (pod) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=\"druid\", pod=~\"druid-sample-.+$\"} * on (namespace,pod) group_left() max by (namespace, pod) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)"
    }
   ]
  },
  { "title": "Memory Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage by Druid pods",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"druid\", pod=~\"druid-sample-.+$\",container!=\"\"} * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, max by (namespace, pod, node) (kube_pod_info{node!=\"\"}))) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"druid\",pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\",container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"druid\",pod=~\"druid-sample-.+$\"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"druid\",pod=~\"druid-sample-.+$\",container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"druid\",pod=~\"druid-sample-.+$\"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"druid\",pod=~\"druid-sample-.+$\"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"druid\",pod=~\"druid-sample-.+$\",container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"druid\",pod=~\"druid-sample-.+$\"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"druid\",pod=~\"druid-sample-.+$\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"druid\",pod=~\"druid-sample-.+$\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"druid\",pod=~\"druid-sample-.+$\",container!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"druid\", pod=~\"druid-sample-.+$\",container!=\"\"} * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, max by (namespace, pod, node) (kube_pod_info{node!=\"\"}))) by (pod) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=\"druid\", pod=~\"druid-sample-.+$\"} * on (namespace,pod) group_left () max by (namespace,pod) ((kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Storage Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "Disk usage by Druid pods",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_blkio_device_usage_total{namespace=\"druid\", pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk R/W Info",
   "type": "graph",
   "description": "System Disk Usage Information",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{namespace=\"druid\",  pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\"}[5m]))by(pod)",
     "legendFormat": "{{pod}}-disk-write"
    },
    {
     "expr": "sum(rate(container_fs_reads_total{namespace=\"druid\",  pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\"}[5m]))by(pod)",
     "legendFormat": "{{pod}}-disk-read"
    }
   ]
  },
  {
   "title": "IOPS (Reads+Writes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\", namespace=~\"druid\",  pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\"}[5m]) + rate(container_fs_writes_total{container!=\"\" ,namespace=~\"druid\",  pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\"}[5m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ThroughPut (Read+Write)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"druid\",  pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\" ,namespace=~\"druid\",  pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\",  pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\",namespace=~\"druid\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_total{container!=\"\",  pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\",namespace=~\"druid\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\",  pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\",namespace=~\"druid\"}[5m]) + rate(container_fs_writes_total{container!=\"\",pod=~\"druid-sample-\\\\d+$\",namespace=~\"druid\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\",namespace=~\"druid\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\",namespace=~\"druid\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\",namespace=~\"druid\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\",pod=~\"druid-sample-\\\\d+$\",namespace=~\"druid\"}[5m]))"
    }
   ]
  },
  { "title": "Persistent Storage Insight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Allocated Storage",
   "type": "table",
   "description": "This panel describes allocated persistent storage in a table format\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"^druid-sample.*\",namespace=~\"druid\"}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage",
   "type": "bargauge",
   "description": "This panel shows the persistent volume usage in percentage. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes / on(persistentvolumeclaim) group_left(pod) (kubelet_volume_stats_capacity_bytes + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"^druid-sample.*\",namespace=~\"druid\"}) )* 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage History",
   "type": "timeseries",
   "description": "This panel describes the persistent volume usage in a time series. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\",namespace=~\"druid\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Volume Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes / on(persistentvolumeclaim) group_left(pod) (kubelet_volume_stats_capacity_bytes + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"^druid-sample.*\",namespace=~\"druid\"}) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"druid\", pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"druid\", pod=~\"druid-sample-brokers-\\\\d+$|druid-sample-coordinators-\\\\d+$|druid-sample-historicals-\\\\d+$|druid-sample-middlemanagers-\\\\d+$|druid-sample-routers-\\\\d+$|druid-sample-overlords-\\\\d+$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}