{
 "title": "KubeDB / Druid / Pod",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(druid_service_heartbeat{job=~\".+\",namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(druid_service_heartbeat{namespace=~\"$namespace\",job=~\"${app}.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Druid Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$pod - Status",
   "type": "stat",
   "description": "Metric indicating the druid pod is up.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "druid_service_heartbeat{job=\"$app\", namespace=\"$namespace\", pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$pod - ZooKeeper Connection",
   "type": "stat",
   "description": "Indicator of connection status. 1 for connected, 0 for disconnected. Emitted once per monitor period.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "druid_zk_connected{job=\"$app\", pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "JVM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "description": "Used memory",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_jvm_mem_used{job=\"$app\", pod=\"$pod\", namespace=\"$namespace\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "description": "Pool used",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_jvm_pool_used{job=\"$app\", pod=\"$pod\", namespace=\"$namespace\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Bufferpool Count",
   "type": "timeseries",
   "description": "Bufferpool count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "druid_jvm_bufferpool_count{bufferpoolName=\"direct\", job=\"$app\", pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM GC Cpu Total",
   "type": "gauge",
   "description": "Count of CPU time in Nanoseconds spent on garbage collection.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "druid_jvm_gc_cpu_total{job=\"$app\", pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Initial Memory (nonHeap)",
   "type": "stat",
   "description": "Initial nonHeap memory",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "druid_jvm_mem_init{job=\"$app\", pod=\"$pod\", memKind=\"nonheap\", namespace=\"$namespace\"}/ (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Initial Memory (Heap)",
   "type": "stat",
   "description": "Initial Heap memory",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "druid_jvm_mem_init{job=\"$app\", pod=\"$pod\", memKind=\"heap\", namespace=\"$namespace\"}/ (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Max Memory (Heap)",
   "type": "stat",
   "description": "Max memory",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "druid_jvm_mem_max{job=\"$app\", pod=\"$pod\", memKind=\"heap\", namespace=\"$namespace\"}/ (1024 * 1024)"
    }
   ]
  }
 ]
}