{
 "title": "KubeDB / Druid / Database",
 "description": "KubeDB Managed Druid Grafana Dashboard that captures metrics emitted by Druid builtin prometheus exporter.",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(druid_service_heartbeat{job=~\".+\",namespace=~\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Druid Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Druid Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(druid_service_heartbeat{job=\"$app\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(druid_zk_connected{job=\"$app\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Datasources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(count(count_values(\"dataSource\",druid_segment_size{job=\"$app\"})))"
    }
   ]
  },
  {
   "title": "Total Segment Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_segment_size{job=\"$app\"}) / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_task_running_count_created{job=\"$app\"})"
    }
   ]
  },
  {
   "title": "Sucess Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time(druid_task_success_count_created{job=\"$app\"}[$__range])",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Unloaded Segments Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_segment_loadqueue_size{job=\"$app\"}) / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time(druid_task_failed_count_created{job=\"$app\"}[$__range])",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Unloaded Segments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(sum(druid_segment_loadqueue_count{job=\"$app\"}))"
    }
   ]
  },
  { "title": "JVM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_jvm_mem_used{job=\"$app\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_jvm_pool_used{job=\"$app\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Bufferpool Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "druid_jvm_bufferpool_count{bufferpoolName=\"direct\", job=\"$app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM GC Cpu Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "druid_jvm_gc_cpu_total{job=\"$app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Druid Datasource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datasource Size",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(druid_segment_size{job=\"$app\"})"
      }
     ]
    },
    {
     "title": "Datasource Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(druid_segment_size{job=\"$app\"}[$__range])) by (dataSource)",
       "legendFormat": "{{dataSource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingestion Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(druid_ingest_events_processed_total{job=\"$app\"}[$__range])) by (dataSource)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Ingestion Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(druid_ingest_kafka_lag{job=\"$app\"}[$__range]))"
      }
     ]
    }
   ]
  }
 ]
}