{
 "title": "kubedb.com / Pgpool / druid / druid-sample",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Druid Phase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Druid Phase Not Ready",
   "type": "graph",
   "description": "Trigger alert if phase is not ready",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubedb_com_druid_status_phase{app=\"druid-sample\",namespace=\"druid\",phase=\"NotReady\"}",
     "legendFormat": "{{druid}}"
    }
   ]
  },
  {
   "title": "Druid Phase Critical",
   "type": "graph",
   "description": "Trigger alert if phase is critical",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubedb_com_druid_status_phase{app=\"druid-sample\",namespace=\"druid\",phase=\"Critical\"}",
     "legendFormat": "{{druid}}"
    }
   ]
  },
  { "title": "Druid Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Druid Down",
   "type": "graph",
   "description": "Specifies  alert  for Druid service down",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(druid_service_heartbeat{namespace=\"druid\",service=\"druid-sample-stats\"})"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnected",
   "type": "graph",
   "description": "Specifies  alert  for Druid lost connection to ZooKeeper",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(druid_zk_connected{namespace=\"druid\",service=\"druid-sample-stats\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Druid Query Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "High Query Time",
   "type": "graph",
   "description": "Druid took more than 1 second to complete a query.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max without(le) (druid_query_time_bucket{service=\"druid-sample-stats\",namespace=\"druid\",le=\"+Inf\", pod=~\".*historicals-0\"} - on(dataSource, type) group_left(le) druid_query_time_bucket{service=\"druid-sample-stats\",namespace=\"druid\",le=\"1.0\", pod=~\".*historicals-0\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "High Query Wait TIme",
   "type": "graph",
   "description": "Druid spent more than 1 sec on waiting for a segment to be scanned.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_query_wait_time_bucket{service=\"druid-sample-stats\",namespace=\"druid\",pod=~\".*historicals-0\",le=\"+Inf\"}- on() druid_query_wait_time_bucket{service=\"druid-sample-stats\",namespace=\"druid\",pod=~\".*historicals-0\",le=\"0.1\"}"
    }
   ]
  },
  { "title": "Druid Segment Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "High Num of Segment Scan Pending",
   "type": "graph",
   "description": "More than 2 segments are in queue waiting to be scanned for more than 1 min.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(druid_segment_scan_pending{service=\"druid-sample-stats\",namespace=\"druid\"})",
     "legendFormat": "{{pod}} ({{role}})"
    }
   ]
  },
  {
   "title": "High Percent of Segment Used",
   "type": "graph",
   "description": "More than 95% of space used by served segments.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(druid_segment_usedpercent{service=\"druid-sample-stats\",namespace=\"druid\"})"
    }
   ]
  },
  { "title": "Druid JVM Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "High JVM Pool Usage Percent",
   "type": "graph",
   "description": "More than 95% of JVM Pool is being used.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(druid_jvm_pool_used{service=\"druid-sample-stats\",namespace=\"druid\"} / on(pod, poolName) druid_jvm_pool_max{service=\"druid-sample-stats\",namespace=\"druid\"}*100)"
    }
   ]
  },
  {
   "title": "High JVM Memory Usage Percentage",
   "type": "graph",
   "description": "More than 95% of JVM Memory is being used.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(druid_jvm_mem_used{service=\"druid-sample-stats\",namespace=\"druid\"}/on(pod, memKind) druid_jvm_mem_max{service=\"druid-sample-stats\",namespace=\"druid\"}*100)"
    }
   ]
  }
 ]
}